language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp3-dev libsigsegv-dev openssl libssl-dev libncurses5-dev git make exuberant-ctags
  
before_script:
  - cd urbit
  - echo "export URBIT_HOME=`pwd`/urb" >>~/.bash_profile
  - make

script: "make --debug=v && pwd && ./CppTesting -v"

notifications
  on_success: change
  on_failure: always
